// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// lovable-mcp-supabase-entry.ts
<<<<<<< HEAD
import mcp from "npm:C:\\Users\\dell\\Desktop\\Kiaan Technology\\radiantilyk-aesthetic\\src\\lib\\mcp\\index.ts";
=======
import mcp from "npm:C:\\Users\\HGP\\Desktop\\intern projects\\Radiantilyk\\radiantilyk-aesthetic\\src\\lib\\mcp\\index.ts";
>>>>>>> cd31bb39e529f5d9fb45d96e8f9ca4fa0c0ed23c
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp, { functionName: "mcp" }));
